---
application:
  name: "mern-project-backend"
  project: "mern-project-memory"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "memories"
routers:
- name: "main-mern-project-backend"
  routes:
  - application_name: "mern-project-backend"
    paths:
    - "/*"
